export interface DashBoardData{
    userCount : number,
    userCountPastWeek : number,
    jobCountPastWeek : number,
    thisWeekUserCount: number,
    pastWeekUserCount : number,
    weekDailyCounts : number[],
    thisMonthUserCount: number,
    pastMonthUserCount : number,
    thisMonthJobCount: number,
    pastMonthJobCount : number,
    jobCount : number,
    thisMonthClosedJobs : number,
    pastMonthClosedJobs : number,
}
